-- User test data
INSERT INTO USER (FIRSTNAME, LASTNAME) VALUES ('John', 'Doe');
INSERT INTO USER (FIRSTNAME, LASTNAME) VALUES ('Max', 'Mustermann');
INSERT INTO USER (FIRSTNAME, LASTNAME) VALUES ('Mary', 'Jane');

-- other tables TODO